[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
reqwest = {version = "*", features = ["json"]}
serde = {version = "*", features = ["derive"]}
serde_json = "*"
tokio = {version = "*", features = ["full"]}

[[bin]]
name = "auth_tdx"
path = "src/auth_tdx.rs"
